; PlatformIO — Módulo Principal
; Controle Remoto para Carrinho de Jet Ski
;
; Painel central (mestre): ESP32 WROOM-32U
; Comunicação: ESP-NOW peer-to-peer

[env:main_firmware]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DPRINCIPAL
    -Wall
    -Wextra
