; PlatformIO — Módulo Remote
; Controle Remoto para Carrinho de Jet Ski
;
; Painel embarcado no carrinho (escravo): ESP32 WROOM-32U
; Comunicação: ESP-NOW peer-to-peer

[env:remote]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
    -DREMOTE
    -Wall
    -Wextra
