; PlatformIO — Módulo Remote
; Controle Remoto para Carrinho de Jet Ski
;
; Painel embarcado no carrinho (escravo): ESP32 WROOM-32U
; Comunicação: ESP-NOW peer-to-peer

[env:remote_firmware]
platform = espressif32
port_monitor = /dev/ttyUSB1
port_upload = /dev/ttyUSB1
board = esp32dev
framework = arduino
monitor_speed = 115200
extra_scripts = pre:../tools/load_security_env.py
build_flags =
    -DREMOTE
    -Wall
    -Wextra
